[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
# Default legacy backend builder PEP 517
build-backend = "setuptools.build_meta:__legacy__"